---

- name: Get subnet facts based on Tier tag
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      "tag-value": "{{ item }}"
  with_items: "{{ subnet_tag }}"
  when: subnet_tag is defined
  register: ec2_subnets

- debug: var=ec2_subnets

- set_fact:
    subnet_ids: "{{ ec2_subnets.results.0.subnets|map(attribute='id')|list }}"
  when: ec2_subnets.results is defined

- debug: var=subnet_ids
