---
# tasks file for get-subnets

- import_tasks: get-vpc-info.yml
- import_tasks: subnet_facts_on_name.yml
  when: subnet_name is defined
- import_tasks: subnet_facts_on_tier.yml
  when: subnet_tier is defined
- import_tasks: subnet_facts_on_env_tier.yml
  when: subnet_env_tier is defined

#- debug: var=subnet_ids
