---

- name: Get Subnet facts from tier tags
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_id }}"
      "tag:Tier": "{{ subnet_tier }}"
  register: ec2_subnets

- debug: var=subnet_tier

- debug: var=ec2_subnets

- name: Set subnet ID's in fact
  set_fact:
    subnet_ids: "{{ ec2_subnets.subnets|map(attribute='id')|list }}"
  when: ec2_subnets is defined

- include_tasks: az_tags.yml
  when: subnet_has_az_tags is defined

- debug: var=subnet_ids
